services:
  api:
    build:
      context: .
      dockerfile: "Dockerfile"
    image: dakpanffs/slijterij:1.0
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app/
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d
      - slijterij_mysql_volume:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${DBPASS}"
      MYSQL_DATABASE: "${DBNAME}"
    networks:
      - default

networks:
  default:

volumes:
  slijterij_mysql_volume:
